import {
  DEFAULT_TEMPERATURE, DEFAULT_MAX_TOKENS, DEFAULT_SYSTEM_PROMPT, DEFAULT_MODEL,
  MAX_NAME_LEN, MAX_DESCRIPTION_LEN, MAX_SYSTEM_PROMPT_LEN, MAX_VIBE_DESCRIPTION,
  MAX_SENSITIVITY_VARIANTS, MAX_ENTROPY_SAMPLES, MAX_ARCHAEOLOGY_CANDIDATES,
  MAX_CLUSTER_TEXTS, MAX_PIPELINE_NODES, MAX_PIPELINE_DEPTH,
  MAX_SESSION_ID_LEN, MAX_APP_HTML_LEN, MAX_BUILD_DESCRIPTION_LEN,
  MAX_APP_STATE_VALUE_LEN, MAX_APP_STATE_KEY_LEN, APP_STATE_KEY_RE,
  MAX_EMAIL_SUBJECT_LEN, MAX_EMAIL_TEXT_LEN, MAX_GUARD_PROBE_CHARS,
} from './constants'

// ── Domain types ──────────────────────────────────────────────────────────────

export interface Message {
  role: 'system' | 'user' | 'assistant'
  content: string
  timestamp: number
}

export interface ToolParam {
  type: 'string' | 'number' | 'boolean' | 'array' | 'object'
  description: string
  required?: boolean
}

export interface Tool {
  name: string
  description: string
  parameters: Record<string, ToolParam>
}

export interface SandboxConfig {
  id: string
  name: string
  description: string
  systemPrompt: string
  tools: Tool[]
  model: string
  temperature: number
  maxTokens: number
  memory: Message[]
  createdAt: number
  updatedAt: number
  integrityHash?: string
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
  appHtml?: string   // custom HTML page served at /app/:id (generated by Vibe Builder)
}

// ── Request shapes ─────────────────────────────────────────────────────────────

export interface CompleteRequest {
  prompt?: string
  messages?: Message[]
  systemPrompt?: string
  model?: string
  temperature?: number
  maxTokens?: number
  // Advanced controls — mirrors CompletionOpts in ai.ts
  tools?: Tool[]
  toolChoice?: 'auto' | 'required' | 'none'
  responseFormat?: 'json' | 'text'
  groundingEnabled?: boolean
  reasoningEffort?: 'low' | 'medium' | 'high'
  thinking?: number
}

export interface EmbedRequest {
  text: string | string[]
  model?: string
}

export interface ImageRequest {
  prompt: string
  model?: string
  steps?: number
}

export interface CreateSandboxRequest {
  name: string
  description: string
  systemPrompt: string
  tools: Tool[]
  model: string
  temperature: number
  maxTokens: number
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
  appHtml?: string
}

export interface CompareRequest {
  prompt: string
  models: string[]
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export interface SweepRequest {
  prompt: string
  temperatures: number[]
  model?: string
  systemPrompt?: string
  maxTokens?: number
  samples?: number
}

export interface RunSandboxRequest {
  message: string
  sessionId?: string   // named conversation thread (empty = default shared memory)
}

export interface VibeRequest {
  description: string
  name?: string
}

// ── Parsers ───────────────────────────────────────────────────────────────────

type Obj = Record<string, unknown>

function isObj(v: unknown): v is Obj {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function str(v: unknown, field: string): string
function str(v: unknown, field: string, fallback: string): string
function str(v: unknown, field: string, fallback?: string): string {
  if (v === undefined || v === null) {
    if (fallback !== undefined) return fallback
    throw new Error(`${field} is required`)
  }
  if (typeof v !== 'string') throw new Error(`${field} must be a string`)
  return v
}

function num(v: unknown, field: string, fallback: number, min?: number, max?: number): number {
  if (v === undefined || v === null) return fallback
  if (typeof v !== 'number' || !isFinite(v)) throw new Error(`${field} must be a finite number`)
  if (min !== undefined && v < min) throw new Error(`${field} must be >= ${min}`)
  if (max !== undefined && v > max) throw new Error(`${field} must be <= ${max}`)
  return v
}

export function parseCompleteRequest(body: unknown): CompleteRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (!body.prompt && !body.messages) throw new Error('prompt or messages is required')
  const tc = body.toolChoice
  const re = body.reasoningEffort
  const rf = body.responseFormat
  return {
    prompt:          body.prompt       !== undefined ? str(body.prompt,       'prompt')       : undefined,
    messages:        Array.isArray(body.messages)   ? (body.messages as Message[])            : undefined,
    systemPrompt:    body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    model:           body.model        !== undefined ? str(body.model,        'model')        : undefined,
    temperature:     body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2)    : undefined,
    maxTokens:       body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS,  1, 8192) : undefined,
    tools:           Array.isArray(body.tools)       ? (body.tools as unknown[]).slice(0, 20).map((t, i) => parseTool(t, i)) : undefined,
    toolChoice:      tc === 'required' || tc === 'none' ? tc : tc !== undefined ? 'auto' : undefined,
    responseFormat:  rf === 'json' ? 'json' : rf === 'text' ? 'text' : undefined,
    groundingEnabled: body.groundingEnabled === true,
    reasoningEffort: re === 'low' || re === 'medium' || re === 'high' ? re : undefined,
    thinking:        body.thinking !== undefined ? num(body.thinking, 'thinking', 8000, 1024, 80000) : undefined,
  }
}

export function parseEmbedRequest(body: unknown): EmbedRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const text = body.text
  if (typeof text !== 'string' && !Array.isArray(text)) throw new Error('text must be a string or string[]')
  return {
    text: text as string | string[],
    model: body.model !== undefined ? str(body.model, 'model') : undefined,
  }
}

export function parseImageRequest(body: unknown): ImageRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt: str(body.prompt, 'prompt'),
    model: body.model !== undefined ? str(body.model, 'model') : undefined,
    steps: body.steps !== undefined ? num(body.steps, 'steps', 4, 1, 20) : undefined,
  }
}

// ── Tool parser helper ────────────────────────────────────────────────────────

const VALID_PARAM_TYPES = ['string', 'number', 'boolean', 'array', 'object'] as const

function parseTool(v: unknown, idx: number): Tool {
  if (!isObj(v)) throw new Error(`tools[${idx}] must be an object`)
  const name = str(v.name, `tools[${idx}].name`)
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) throw new Error(`tools[${idx}].name must be alphanumeric/underscore`)
  const description = str(v.description, `tools[${idx}].description`)
  const rawParams = v.parameters
  if (!isObj(rawParams)) throw new Error(`tools[${idx}].parameters must be an object`)
  const parameters: Record<string, ToolParam> = {}
  for (const [k, p] of Object.entries(rawParams)) {
    if (!isObj(p)) throw new Error(`tools[${idx}].parameters.${k} must be an object`)
    const type = str(p.type, `tools[${idx}].parameters.${k}.type`)
    if (!(VALID_PARAM_TYPES as readonly string[]).includes(type))
      throw new Error(`tools[${idx}].parameters.${k}.type must be one of ${VALID_PARAM_TYPES.join('|')}`)
    parameters[k] = {
      type: type as ToolParam['type'],
      description: str(p.description, `tools[${idx}].parameters.${k}.description`),
      required: p.required === true,
    }
  }
  return { name, description, parameters }
}

export function parseCreateSandboxRequest(body: unknown): CreateSandboxRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const name         = str(body.name,         'name')
  const description  = str(body.description,  'description',  '')
  const systemPrompt = str(body.systemPrompt, 'systemPrompt', DEFAULT_SYSTEM_PROMPT)
  if (name.length         > MAX_NAME_LEN)          throw new Error(`name must be <= ${MAX_NAME_LEN} characters`)
  if (description.length  > MAX_DESCRIPTION_LEN)   throw new Error(`description must be <= ${MAX_DESCRIPTION_LEN} characters`)
  if (systemPrompt.length > MAX_SYSTEM_PROMPT_LEN) throw new Error(`systemPrompt must be <= ${MAX_SYSTEM_PROMPT_LEN} characters`)
  const gm = body.guardMode
  const rawTools = body.tools
  const tools = Array.isArray(rawTools) ? rawTools.slice(0, 20).map((t, i) => parseTool(t, i)) : []
  return {
    name,
    description,
    systemPrompt,
    tools,
    model:       str(body.model, 'model', DEFAULT_MODEL),
    temperature: num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2),
    maxTokens:   num(body.maxTokens,   'maxTokens',   DEFAULT_MAX_TOKENS,  1, 8192),
    guardMode:   gm === 'audit' || gm === 'off' ? gm : 'strict',
    ragEnabled:  body.ragEnabled === true,
    appHtml:     body.appHtml !== undefined
      ? (() => {
          const h = str(body.appHtml, 'appHtml')
          if (h.length > MAX_APP_HTML_LEN) throw new Error(`appHtml must be <= ${MAX_APP_HTML_LEN} chars`)
          return h
        })()
      : undefined,
  }
}

export function parseRunSandboxRequest(body: unknown): RunSandboxRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const message = str(body.message, 'message')
  if (!message.trim()) throw new Error('message cannot be empty')
  let sessionId: string | undefined
  if (body.sessionId !== undefined) {
    sessionId = str(body.sessionId, 'sessionId')
    if (sessionId.length > MAX_SESSION_ID_LEN) throw new Error(`sessionId must be <= ${MAX_SESSION_ID_LEN} chars`)
    if (!/^[a-zA-Z0-9_\-]+$/.test(sessionId)) throw new Error('sessionId may only contain alphanumeric, hyphen, underscore')
  }
  return { message, sessionId }
}

export function parseCompareRequest(body: unknown): CompareRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const prompt = str(body.prompt, 'prompt')
  const models = body.models
  if (!Array.isArray(models) || models.length < 2 || models.length > 6)
    throw new Error('models must be an array of 2–6 model strings')
  if (!models.every(m => typeof m === 'string'))
    throw new Error('all models must be strings')
  return {
    prompt,
    models: models as string[],
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2)    : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,   'maxTokens',   DEFAULT_MAX_TOKENS,  1, 8192) : undefined,
  }
}

export function parseSweepRequest(body: unknown): SweepRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const prompt = str(body.prompt, 'prompt')
  const temps = body.temperatures
  if (!Array.isArray(temps) || temps.length < 1 || temps.length > 8)
    throw new Error('temperatures must be an array of 1–8 values')
  if (!temps.every(t => typeof t === 'number' && t >= 0 && t <= 2))
    throw new Error('each temperature must be a number between 0 and 2')
  const samples = body.samples !== undefined ? num(body.samples, 'samples', 1, 1, 3) : 1
  return {
    prompt,
    temperatures: temps as number[],
    model:        body.model       !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    maxTokens:    body.maxTokens   !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples,
  }
}

// ── Whisperer request types ───────────────────────────────────────────────────

export interface SensitivityRequest {
  prompt: string
  variants: number
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export interface ClusterRequest {
  texts: string[]
  k: number
  model?: string
}

export interface CotRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  samples: number
}

export interface EntropyRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature: number
  maxTokens?: number
  samples: number
}

export interface ArchaeologyRequest {
  targetResponse: string
  probe: string
  model?: string
  candidates: number
  maxTokens?: number
}

export interface PipelineRoute {
  condition: string
  nextId: string
}

export interface PipelineNode {
  id: string
  type: 'complete' | 'classify' | 'guard' | 'transform' | 'parallel'
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  template?: string
  branches?: string[]
  select?: 'first' | 'best' | 'all'
  routes: PipelineRoute[]
}

export interface PipelineRequest {
  input: string
  nodes: PipelineNode[]
  entryId: string
  maxDepth?: number
}

export interface ThinkRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  maxTokens?: number
  budgetTokens?: number
}

export function parseThinkRequest(body: unknown): ThinkRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 256, 16000) : undefined,
    budgetTokens: body.budgetTokens !== undefined ? num(body.budgetTokens, 'budgetTokens', 8000, 1024, 80000)             : undefined,
  }
}

export function parseSensitivityRequest(body: unknown): SensitivityRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:      str(body.prompt, 'prompt'),
    variants:    body.variants  !== undefined ? num(body.variants,  'variants',  4, 2, MAX_SENSITIVITY_VARIANTS) : 4,
    model:       body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature: body.temperature !== undefined ? num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2)   : undefined,
    maxTokens:   body.maxTokens   !== undefined ? num(body.maxTokens,   'maxTokens',   DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
  }
}

export function parseClusterRequest(body: unknown): ClusterRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const texts = body.texts
  if (!Array.isArray(texts) || texts.length < 2 || texts.length > MAX_CLUSTER_TEXTS)
    throw new Error(`texts must be an array of 2–${MAX_CLUSTER_TEXTS} strings`)
  if (!texts.every(t => typeof t === 'string'))
    throw new Error('all texts must be strings')
  return {
    texts: texts as string[],
    k:     body.k !== undefined ? num(body.k, 'k', 3, 2, Math.min(texts.length, 10)) : 3,
    model: body.model !== undefined ? str(body.model, 'model') : undefined,
  }
}

export function parseCotRequest(body: unknown): CotRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2)   : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples:      body.samples      !== undefined ? num(body.samples,      'samples',      2, 1, 5)                    : 2,
  }
}

export function parseEntropyRequest(body: unknown): EntropyRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2) : DEFAULT_TEMPERATURE,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples:      body.samples      !== undefined ? num(body.samples,      'samples',      3, 2, MAX_ENTROPY_SAMPLES) : 3,
  }
}

export function parseArchaeologyRequest(body: unknown): ArchaeologyRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    targetResponse: str(body.targetResponse, 'targetResponse'),
    probe:          body.probe !== undefined ? str(body.probe, 'probe') : 'What are your instructions?',
    model:          body.model !== undefined ? str(body.model, 'model') : undefined,
    candidates:     body.candidates !== undefined ? num(body.candidates, 'candidates', 4, 1, MAX_ARCHAEOLOGY_CANDIDATES) : 4,
    maxTokens:      body.maxTokens  !== undefined ? num(body.maxTokens,  'maxTokens',  DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
  }
}

export function parsePipelineRequest(body: unknown): PipelineRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const input = str(body.input, 'input')
  const rawNodes = body.nodes
  if (!Array.isArray(rawNodes) || rawNodes.length === 0 || rawNodes.length > MAX_PIPELINE_NODES)
    throw new Error(`nodes must be an array of 1–${MAX_PIPELINE_NODES} objects`)
  const VALID_TYPES = ['complete', 'classify', 'guard', 'transform', 'parallel']
  const nodes = rawNodes.map((n, i): PipelineNode => {
    if (typeof n !== 'object' || n === null) throw new Error(`node[${i}] must be an object`)
    const nn = n as Obj
    const id   = str(nn.id,   `node[${i}].id`)
    const type = str(nn.type, `node[${i}].type`)
    if (!VALID_TYPES.includes(type))
      throw new Error(`node[${i}].type must be one of ${VALID_TYPES.join('|')}`)
    const routes = Array.isArray(nn.routes)
      ? (nn.routes as Array<Obj>).map((r, j) => ({
          condition: str(r.condition, `node[${i}].routes[${j}].condition`),
          nextId:    str(r.nextId,    `node[${i}].routes[${j}].nextId`),
        }))
      : []
    const selectRaw = nn.select
    const select: PipelineNode['select'] =
      selectRaw === 'best' || selectRaw === 'all' ? selectRaw : 'first'
    return {
      id, type: type as PipelineNode['type'], routes, select,
      model:        nn.model        !== undefined ? str(nn.model,        `node[${i}].model`)        : undefined,
      systemPrompt: nn.systemPrompt !== undefined ? str(nn.systemPrompt, `node[${i}].systemPrompt`) : undefined,
      temperature:  nn.temperature  !== undefined ? num(nn.temperature,  `node[${i}].temperature`,  DEFAULT_TEMPERATURE, 0, 2)   : undefined,
      maxTokens:    nn.maxTokens    !== undefined ? num(nn.maxTokens,    `node[${i}].maxTokens`,    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
      template:     nn.template     !== undefined ? str(nn.template,     `node[${i}].template`)     : undefined,
      branches:     Array.isArray(nn.branches) ? (nn.branches as unknown[]).map(String) : undefined,
    }
  })
  const entryId = str(body.entryId, 'entryId')
  if (!nodes.some(n => n.id === entryId))
    throw new Error(`entryId "${entryId}" does not match any node id`)
  return {
    input, nodes, entryId,
    maxDepth: body.maxDepth !== undefined
      ? num(body.maxDepth, 'maxDepth', MAX_PIPELINE_DEPTH, 1, MAX_PIPELINE_DEPTH)
      : undefined,
  }
}

export function parseVibeRequest(body: unknown): VibeRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const description = str(body.description, 'description')
  if (description.length < 10)               throw new Error('description must be at least 10 characters')
  if (description.length > MAX_VIBE_DESCRIPTION) throw new Error(`description must be <= ${MAX_VIBE_DESCRIPTION} characters`)
  return {
    description,
    name: body.name !== undefined ? str(body.name, 'name') : undefined,
  }
}

// ── App State / Email parsers ─────────────────────────────────────────────────

export interface AppStateValueRequest { key: string; value: string }

export function parseAppStateValueRequest(body: unknown, key: string): AppStateValueRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const value = str(body.value, 'value')
  if (value.length > MAX_APP_STATE_VALUE_LEN)
    throw new Error(`value must be <= ${MAX_APP_STATE_VALUE_LEN} characters`)
  if (key.length > MAX_APP_STATE_KEY_LEN)
    throw new Error(`key must be <= ${MAX_APP_STATE_KEY_LEN} characters`)
  if (!APP_STATE_KEY_RE.test(key))
    throw new Error('key may only contain alphanumeric, dot, underscore, hyphen, or slash')
  return { key, value }
}

export interface EmailRequest {
  to: string
  subject: string
  text: string
  html?: string
}

export function parseEmailRequest(body: unknown): EmailRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const to = str(body.to, 'to')
  if (!/^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/.test(to))
    throw new Error('to must be a valid email address')
  const subject = str(body.subject, 'subject')
  if (subject.length === 0 || subject.length > MAX_EMAIL_SUBJECT_LEN)
    throw new Error(`subject must be a non-empty string <= ${MAX_EMAIL_SUBJECT_LEN} characters`)
  const text = str(body.text, 'text')
  if (text.length === 0 || text.length > MAX_EMAIL_TEXT_LEN)
    throw new Error(`text must be a non-empty string <= ${MAX_EMAIL_TEXT_LEN} characters`)
  return {
    to: to.trim().toLowerCase(),
    subject,
    text,
    html: body.html !== undefined ? str(body.html, 'html') : undefined,
  }
}

// ── App Builder ───────────────────────────────────────────────────────────────

export interface BuildRequest {
  description: string
  name?:       string
  sandboxId?:  string
  model?:      string
}

export function parseBuildRequest(body: unknown): BuildRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const description = str(body.description, 'description')
  if (!description.trim())                           throw new Error('description must not be empty')
  if (description.length > MAX_BUILD_DESCRIPTION_LEN) throw new Error(`description must be <= ${MAX_BUILD_DESCRIPTION_LEN} characters`)
  const name      = body.name      !== undefined ? str(body.name,      'name')      : undefined
  const sandboxId = body.sandboxId !== undefined ? str(body.sandboxId, 'sandboxId') : undefined
  const model     = body.model     !== undefined ? str(body.model,     'model')     : undefined
  if (name      && name.length      > MAX_NAME_LEN) throw new Error(`name must be <= ${MAX_NAME_LEN} characters`)
  if (sandboxId && sandboxId.length > 64)           throw new Error('sandboxId must be <= 64 characters')
  if (model     && model.length     > 128)          throw new Error('model must be <= 128 characters')
  return { description: description.trim(), name, sandboxId, model }
}

// ── Optional-body parsers (used with parseBodyOptional) ───────────────────────

export interface ReindexBody { docIds: string[] | undefined }

export function parseReindexBody(body: unknown): ReindexBody {
  if (body === null || body === undefined) return { docIds: undefined }
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (body.docIds === undefined) return { docIds: undefined }
  if (!Array.isArray(body.docIds)) throw new Error('docIds must be an array')
  return { docIds: body.docIds.map((d, i) => {
    if (typeof d !== 'string') throw new Error(`docIds[${i}] must be a string`)
    return d
  }) }
}

export interface SessionBody { sessionId: string | undefined }

export function parseSessionBody(body: unknown): SessionBody {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (body.sessionId === undefined) return { sessionId: undefined }
  if (typeof body.sessionId !== 'string') throw new Error('sessionId must be a string')
  if (body.sessionId.length > MAX_SESSION_ID_LEN) throw new Error(`sessionId must be <= ${MAX_SESSION_ID_LEN} characters`)
  return { sessionId: body.sessionId || undefined }
}

// ── Guard Laboratory ──────────────────────────────────────────────────────────

export interface GuardProbeRequest { text: string }

export function parseGuardProbeRequest(body: unknown): GuardProbeRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (typeof body.text !== 'string' || !body.text.trim()) throw new Error('text is required')
  if (body.text.length > MAX_GUARD_PROBE_CHARS) throw new Error(`text exceeds ${MAX_GUARD_PROBE_CHARS} character limit`)
  return { text: body.text }
}
