import {
  DEFAULT_TEMPERATURE, DEFAULT_MAX_TOKENS, DEFAULT_SYSTEM_PROMPT, DEFAULT_MODEL,
  MAX_NAME_LEN, MAX_DESCRIPTION_LEN, MAX_SYSTEM_PROMPT_LEN, MAX_VIBE_DESCRIPTION,
  MAX_SENSITIVITY_VARIANTS, MAX_ENTROPY_SAMPLES, MAX_ARCHAEOLOGY_CANDIDATES,
  MAX_CLUSTER_TEXTS, MAX_PIPELINE_NODES, MAX_PIPELINE_DEPTH,
  MAX_SESSION_ID_LEN, MAX_APP_HTML_LEN, MAX_BUILD_DESCRIPTION_LEN,
  MAX_APP_STATE_VALUE_LEN, MAX_APP_STATE_KEY_LEN, APP_STATE_KEY_RE,
  MAX_EMAIL_SUBJECT_LEN, MAX_EMAIL_TEXT_LEN, MAX_GUARD_PROBE_CHARS, MAX_ABLATION_CLAUSES,
  MAX_DRIFT_TURNS, MAX_STRESS_LEVELS, MAX_RUBRIC_CRITERIA, MAX_RUBRIC_SAMPLES,
  MAX_WEBHOOK_URL_LEN, MAX_IMAGE_BASE64_BYTES, MAX_IMAGES_PER_MESSAGE, MAX_JSON_SCHEMA_BYTES,
  MAX_TTS_TEXT_LEN, AI_SEARCH_MAX_RESULTS, USAGE_LIMIT_DEFAULT, USAGE_LIMIT_MAX,
  MAX_ENV_MODELS, ENV_TYPES,
} from './constants'
import { parseQueryInt } from './http'

// ── Domain types ──────────────────────────────────────────────────────────────

export interface TextBlock {
  type: 'text'
  text: string
}

export interface ImageBlock {
  type: 'image'
  mediaType: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp'
  data: string  // base64, no data: URI prefix
}

export type ContentBlock = TextBlock | ImageBlock

export interface Message {
  role: 'system' | 'user' | 'assistant'
  content: string | ContentBlock[]
  timestamp: number
}

export interface ToolParam {
  type: 'string' | 'number' | 'boolean' | 'array' | 'object'
  description: string
  required?: boolean
}

export interface Tool {
  name: string
  description: string
  parameters: Record<string, ToolParam>
}

export interface SandboxConfig {
  id: string
  name: string
  description: string
  systemPrompt: string
  tools: Tool[]
  model: string
  temperature: number
  maxTokens: number
  memory: Message[]
  createdAt: number
  updatedAt: number
  integrityHash?: string
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
  appHtml?: string   // custom HTML page served at /app/:id (generated by Vibe Builder)
  envType?: string   // chat environment type: general | coding | research | structured
  envModels?: string[]  // ordered model list for compare mode (1–MAX_ENV_MODELS)
}

// ── Request shapes ─────────────────────────────────────────────────────────────

export interface CompleteRequest {
  prompt?: string
  messages?: Message[]
  systemPrompt?: string
  model?: string
  temperature?: number
  maxTokens?: number
  // Advanced controls — mirrors CompletionOpts in ai.ts
  tools?: Tool[]
  toolChoice?: 'auto' | 'required' | 'none'
  responseFormat?: 'json' | 'text'
  jsonSchema?: Record<string, unknown>  // OpenAI json_schema strict mode (overrides responseFormat)
  groundingEnabled?: boolean
  reasoningEffort?: 'low' | 'medium' | 'high'
  thinking?: number
  // AI Gateway extended controls
  byokAlias?:        string   // cf-aig-byok-alias — named credential in Secrets Store
  zdr?:              boolean  // cf-aig-zdr: true — Zero Data Retention (Unified Billing only)
  collectLogPayload?: boolean // false → cf-aig-collect-log-payload: false (suppress body logging)
  fallbackModel?:    string   // tried once if the primary model throws
}

export interface EmbedRequest {
  text: string | string[]
  model?: string
}

export interface ImageRequest {
  prompt: string
  model?: string
  steps?: number
}

export interface CreateSandboxRequest {
  name: string
  description: string
  systemPrompt: string
  tools: Tool[]
  model: string
  temperature: number
  maxTokens: number
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
  appHtml?: string
}

export interface CompareRequest {
  prompt: string
  models: string[]
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export interface SweepRequest {
  prompt: string
  temperatures: number[]
  model?: string
  systemPrompt?: string
  maxTokens?: number
  samples?: number
}

export interface RunSandboxRequest {
  message: string
  sessionId?: string   // named conversation thread (empty = default shared memory)
}

export interface VibeRequest {
  description: string
  name?: string
}

export interface EnvironmentRequest {
  description: string
  envType: string
  envModels?: string[]
  name?: string
}

// ── Parsers ───────────────────────────────────────────────────────────────────

type Obj = Record<string, unknown>

function isObj(v: unknown): v is Obj {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

const ALLOWED_IMAGE_MEDIA_TYPES = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp'])

function parseContentBlock(v: unknown, idx: number): ContentBlock {
  if (!isObj(v)) throw new Error(`content[${idx}] must be an object`)
  const { type } = v
  if (type === 'text') {
    if (typeof v.text !== 'string') throw new Error(`content[${idx}].text must be a string`)
    return { type: 'text', text: v.text }
  }
  if (type === 'image') {
    if (!ALLOWED_IMAGE_MEDIA_TYPES.has(v.mediaType as string))
      throw new Error(`content[${idx}].mediaType must be image/jpeg, image/png, image/gif, or image/webp`)
    if (typeof v.data !== 'string' || v.data.length === 0)
      throw new Error(`content[${idx}].data must be a non-empty base64 string`)
    if (v.data.length > MAX_IMAGE_BASE64_BYTES)
      throw new Error(`content[${idx}].data exceeds maximum allowed size`)
    return { type: 'image', mediaType: v.mediaType as ImageBlock['mediaType'], data: v.data as string }
  }
  throw new Error(`content[${idx}].type must be "text" or "image"`)
}

function parseMessageContent(v: unknown): string | ContentBlock[] {
  if (typeof v === 'string') return v
  if (Array.isArray(v)) {
    if (v.length > MAX_IMAGES_PER_MESSAGE + 20)
      throw new Error(`content array exceeds maximum length`)
    const imageCount = v.filter(b => isObj(b) && (b as Obj).type === 'image').length
    if (imageCount > MAX_IMAGES_PER_MESSAGE)
      throw new Error(`messages may contain at most ${MAX_IMAGES_PER_MESSAGE} images`)
    return v.map((b, i) => parseContentBlock(b, i))
  }
  throw new Error('message content must be a string or array of content blocks')
}

function parseMessage(v: unknown, idx: number): Message {
  if (!isObj(v)) throw new Error(`messages[${idx}] must be an object`)
  const role = v.role
  if (role !== 'system' && role !== 'user' && role !== 'assistant')
    throw new Error(`messages[${idx}].role must be "system", "user", or "assistant"`)
  if (v.content === undefined) throw new Error(`messages[${idx}].content is required`)
  const content = parseMessageContent(v.content)
  const timestamp = typeof v.timestamp === 'number' ? v.timestamp : 0
  return { role: role as Message['role'], content, timestamp }
}

function str(v: unknown, field: string): string
function str(v: unknown, field: string, fallback: string): string
function str(v: unknown, field: string, fallback?: string): string {
  if (v === undefined || v === null) {
    if (fallback !== undefined) return fallback
    throw new Error(`${field} is required`)
  }
  if (typeof v !== 'string') throw new Error(`${field} must be a string`)
  return v
}

function num(v: unknown, field: string, fallback: number, min?: number, max?: number): number {
  if (v === undefined || v === null) return fallback
  if (typeof v !== 'number' || !isFinite(v)) throw new Error(`${field} must be a finite number`)
  if (min !== undefined && v < min) throw new Error(`${field} must be >= ${min}`)
  if (max !== undefined && v > max) throw new Error(`${field} must be <= ${max}`)
  return v
}

function bool(v: unknown, field: string, fallback: boolean): boolean {
  if (!isObj(v)) return fallback
  const val = (v as Record<string, unknown>)[field]
  if (val === undefined || val === null) return fallback
  if (typeof val !== 'boolean') throw new Error(`${field} must be a boolean`)
  return val
}

export function parseCompleteRequest(body: unknown): CompleteRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (!body.prompt && !body.messages) throw new Error('prompt or messages is required')
  const tc = body.toolChoice
  const re = body.reasoningEffort
  const rf = body.responseFormat
  let jsonSchema: Record<string, unknown> | undefined
  if (body.jsonSchema !== undefined) {
    if (!isObj(body.jsonSchema)) throw new Error('jsonSchema must be an object')
    if (JSON.stringify(body.jsonSchema).length > MAX_JSON_SCHEMA_BYTES)
      throw new Error(`jsonSchema must be <= ${MAX_JSON_SCHEMA_BYTES} bytes`)
    jsonSchema = body.jsonSchema as Record<string, unknown>
  }
  return {
    prompt:          body.prompt       !== undefined ? str(body.prompt,       'prompt')       : undefined,
    messages:        Array.isArray(body.messages)   ? body.messages.map((m, i) => parseMessage(m, i)) : undefined,
    systemPrompt:    body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    model:           body.model        !== undefined ? str(body.model,        'model')        : undefined,
    temperature:     body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2)    : undefined,
    maxTokens:       body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS,  1, 8192) : undefined,
    tools:           Array.isArray(body.tools)       ? (body.tools as unknown[]).slice(0, 20).map((t, i) => parseTool(t, i)) : undefined,
    toolChoice:      tc === 'required' || tc === 'none' ? tc : tc !== undefined ? 'auto' : undefined,
    responseFormat:  rf === 'json' ? 'json' : rf === 'text' ? 'text' : undefined,
    jsonSchema,
    groundingEnabled:  bool(body, 'groundingEnabled', false),
    reasoningEffort:   re === 'low' || re === 'medium' || re === 'high' ? re : undefined,
    thinking:          body.thinking !== undefined ? num(body.thinking, 'thinking', 8000, 1024, 80000) : undefined,
    byokAlias:         body.byokAlias    !== undefined ? str(body.byokAlias, 'byokAlias') : undefined,
    zdr:               bool(body, 'zdr', false),
    collectLogPayload: body.collectLogPayload !== undefined ? bool(body, 'collectLogPayload', false) : undefined,
    fallbackModel:     body.fallbackModel !== undefined ? str(body.fallbackModel, 'fallbackModel') : undefined,
  }
}

export function parseEmbedRequest(body: unknown): EmbedRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const text = body.text
  if (typeof text !== 'string' && !Array.isArray(text)) throw new Error('text must be a string or string[]')
  return {
    text: text as string | string[],
    model: body.model !== undefined ? str(body.model, 'model') : undefined,
  }
}

export function parseImageRequest(body: unknown): ImageRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt: str(body.prompt, 'prompt'),
    model: body.model !== undefined ? str(body.model, 'model') : undefined,
    steps: body.steps !== undefined ? num(body.steps, 'steps', 4, 1, 20) : undefined,
  }
}

// ── Tool parser helper ────────────────────────────────────────────────────────

const VALID_PARAM_TYPES = ['string', 'number', 'boolean', 'array', 'object'] as const

function parseTool(v: unknown, idx: number): Tool {
  if (!isObj(v)) throw new Error(`tools[${idx}] must be an object`)
  const name = str(v.name, `tools[${idx}].name`)
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) throw new Error(`tools[${idx}].name must be alphanumeric/underscore`)
  const description = str(v.description, `tools[${idx}].description`)
  const rawParams = v.parameters
  if (!isObj(rawParams)) throw new Error(`tools[${idx}].parameters must be an object`)
  const parameters: Record<string, ToolParam> = {}
  for (const [k, p] of Object.entries(rawParams)) {
    if (!isObj(p)) throw new Error(`tools[${idx}].parameters.${k} must be an object`)
    const type = str(p.type, `tools[${idx}].parameters.${k}.type`)
    if (!(VALID_PARAM_TYPES as readonly string[]).includes(type))
      throw new Error(`tools[${idx}].parameters.${k}.type must be one of ${VALID_PARAM_TYPES.join('|')}`)
    parameters[k] = {
      type: type as ToolParam['type'],
      description: str(p.description, `tools[${idx}].parameters.${k}.description`),
      required: p.required === true,
    }
  }
  return { name, description, parameters }
}

export function parseCreateSandboxRequest(body: unknown): CreateSandboxRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const name         = str(body.name,         'name')
  const description  = str(body.description,  'description',  '')
  const systemPrompt = str(body.systemPrompt, 'systemPrompt', DEFAULT_SYSTEM_PROMPT)
  if (name.length         > MAX_NAME_LEN)          throw new Error(`name must be <= ${MAX_NAME_LEN} characters`)
  if (description.length  > MAX_DESCRIPTION_LEN)   throw new Error(`description must be <= ${MAX_DESCRIPTION_LEN} characters`)
  if (systemPrompt.length > MAX_SYSTEM_PROMPT_LEN) throw new Error(`systemPrompt must be <= ${MAX_SYSTEM_PROMPT_LEN} characters`)
  const gm = body.guardMode
  const rawTools = body.tools
  const tools = Array.isArray(rawTools) ? rawTools.slice(0, 20).map((t, i) => parseTool(t, i)) : []
  return {
    name,
    description,
    systemPrompt,
    tools,
    model:       str(body.model, 'model', DEFAULT_MODEL),
    temperature: num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2),
    maxTokens:   num(body.maxTokens,   'maxTokens',   DEFAULT_MAX_TOKENS,  1, 8192),
    guardMode:   gm === 'audit' || gm === 'off' ? gm : 'strict',
    ragEnabled:  bool(body, 'ragEnabled', false),
    appHtml:     body.appHtml !== undefined
      ? (() => {
          const h = str(body.appHtml, 'appHtml')
          if (h.length > MAX_APP_HTML_LEN) throw new Error(`appHtml must be <= ${MAX_APP_HTML_LEN} chars`)
          return h
        })()
      : undefined,
  }
}

export function parseRunSandboxRequest(body: unknown): RunSandboxRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const message = str(body.message, 'message')
  if (!message.trim()) throw new Error('message cannot be empty')
  let sessionId: string | undefined
  if (body.sessionId !== undefined) {
    sessionId = str(body.sessionId, 'sessionId')
    if (sessionId.length > MAX_SESSION_ID_LEN) throw new Error(`sessionId must be <= ${MAX_SESSION_ID_LEN} chars`)
    if (!/^[a-zA-Z0-9_\-]+$/.test(sessionId)) throw new Error('sessionId may only contain alphanumeric, hyphen, underscore')
  }
  return { message, sessionId }
}

export function parseCompareRequest(body: unknown): CompareRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const prompt = str(body.prompt, 'prompt')
  const models = body.models
  if (!Array.isArray(models) || models.length < 2 || models.length > 6)
    throw new Error('models must be an array of 2–6 model strings')
  if (!models.every(m => typeof m === 'string'))
    throw new Error('all models must be strings')
  return {
    prompt,
    models: models as string[],
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2)    : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,   'maxTokens',   DEFAULT_MAX_TOKENS,  1, 8192) : undefined,
  }
}

export function parseSweepRequest(body: unknown): SweepRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const prompt = str(body.prompt, 'prompt')
  const temps = body.temperatures
  if (!Array.isArray(temps) || temps.length < 1 || temps.length > 8)
    throw new Error('temperatures must be an array of 1–8 values')
  if (!temps.every(t => typeof t === 'number' && t >= 0 && t <= 2))
    throw new Error('each temperature must be a number between 0 and 2')
  const samples = body.samples !== undefined ? num(body.samples, 'samples', 1, 1, 3) : 1
  return {
    prompt,
    temperatures: temps as number[],
    model:        body.model       !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    maxTokens:    body.maxTokens   !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples,
  }
}

// ── Whisperer request types ───────────────────────────────────────────────────

export interface SensitivityRequest {
  prompt: string
  variants: number
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export interface ClusterRequest {
  texts: string[]
  k: number
  model?: string
}

export interface CotRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  samples: number
}

export interface EntropyRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature: number
  maxTokens?: number
  samples: number
}

export interface ArchaeologyRequest {
  targetResponse: string
  probe: string
  model?: string
  candidates: number
  maxTokens?: number
}

export interface PipelineRoute {
  condition: string
  nextId: string
}

export interface PipelineNode {
  id: string
  type: 'complete' | 'classify' | 'guard' | 'transform' | 'parallel' | 'env_resolve'
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  template?: string
  branches?: string[]
  select?: 'first' | 'best' | 'all'
  envId?: string  // for env_resolve: resolves environment config and outputs it as JSON
  routes: PipelineRoute[]
}

export interface PipelineRequest {
  input: string
  nodes: PipelineNode[]
  entryId: string
  maxDepth?: number
}

export interface ThinkRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  maxTokens?: number
  budgetTokens?: number
}

export function parseThinkRequest(body: unknown): ThinkRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 256, 16000) : undefined,
    budgetTokens: body.budgetTokens !== undefined ? num(body.budgetTokens, 'budgetTokens', 8000, 1024, 80000)             : undefined,
  }
}

export function parseSensitivityRequest(body: unknown): SensitivityRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:      str(body.prompt, 'prompt'),
    variants:    body.variants  !== undefined ? num(body.variants,  'variants',  4, 2, MAX_SENSITIVITY_VARIANTS) : 4,
    model:       body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature: body.temperature !== undefined ? num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2)   : undefined,
    maxTokens:   body.maxTokens   !== undefined ? num(body.maxTokens,   'maxTokens',   DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
  }
}

export function parseClusterRequest(body: unknown): ClusterRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const texts = body.texts
  if (!Array.isArray(texts) || texts.length < 2 || texts.length > MAX_CLUSTER_TEXTS)
    throw new Error(`texts must be an array of 2–${MAX_CLUSTER_TEXTS} strings`)
  if (!texts.every(t => typeof t === 'string'))
    throw new Error('all texts must be strings')
  return {
    texts: texts as string[],
    k:     body.k !== undefined ? num(body.k, 'k', 3, 2, Math.min(texts.length, 10)) : 3,
    model: body.model !== undefined ? str(body.model, 'model') : undefined,
  }
}

export function parseCotRequest(body: unknown): CotRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2)   : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples:      body.samples      !== undefined ? num(body.samples,      'samples',      2, 1, 5)                    : 2,
  }
}

export function parseEntropyRequest(body: unknown): EntropyRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2) : DEFAULT_TEMPERATURE,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples:      body.samples      !== undefined ? num(body.samples,      'samples',      3, 2, MAX_ENTROPY_SAMPLES) : 3,
  }
}

export function parseArchaeologyRequest(body: unknown): ArchaeologyRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    targetResponse: str(body.targetResponse, 'targetResponse'),
    probe:          body.probe !== undefined ? str(body.probe, 'probe') : 'What are your instructions?',
    model:          body.model !== undefined ? str(body.model, 'model') : undefined,
    candidates:     body.candidates !== undefined ? num(body.candidates, 'candidates', 4, 1, MAX_ARCHAEOLOGY_CANDIDATES) : 4,
    maxTokens:      body.maxTokens  !== undefined ? num(body.maxTokens,  'maxTokens',  DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
  }
}

export function parsePipelineRequest(body: unknown): PipelineRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const input = str(body.input, 'input')
  const rawNodes = body.nodes
  if (!Array.isArray(rawNodes) || rawNodes.length === 0 || rawNodes.length > MAX_PIPELINE_NODES)
    throw new Error(`nodes must be an array of 1–${MAX_PIPELINE_NODES} objects`)
  const VALID_TYPES = ['complete', 'classify', 'guard', 'transform', 'parallel', 'env_resolve']
  const nodes = rawNodes.map((n, i): PipelineNode => {
    if (typeof n !== 'object' || n === null) throw new Error(`node[${i}] must be an object`)
    const nn = n as Obj
    const id   = str(nn.id,   `node[${i}].id`)
    const type = str(nn.type, `node[${i}].type`)
    if (!VALID_TYPES.includes(type))
      throw new Error(`node[${i}].type must be one of ${VALID_TYPES.join('|')}`)
    const routes = Array.isArray(nn.routes)
      ? (nn.routes as Array<Obj>).map((r, j) => ({
          condition: str(r.condition, `node[${i}].routes[${j}].condition`),
          nextId:    str(r.nextId,    `node[${i}].routes[${j}].nextId`),
        }))
      : []
    const selectRaw = nn.select
    const select: PipelineNode['select'] =
      selectRaw === 'best' || selectRaw === 'all' ? selectRaw : 'first'
    return {
      id, type: type as PipelineNode['type'], routes, select,
      model:        nn.model        !== undefined ? str(nn.model,        `node[${i}].model`)        : undefined,
      systemPrompt: nn.systemPrompt !== undefined ? str(nn.systemPrompt, `node[${i}].systemPrompt`) : undefined,
      temperature:  nn.temperature  !== undefined ? num(nn.temperature,  `node[${i}].temperature`,  DEFAULT_TEMPERATURE, 0, 2)   : undefined,
      maxTokens:    nn.maxTokens    !== undefined ? num(nn.maxTokens,    `node[${i}].maxTokens`,    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
      template:     nn.template     !== undefined ? str(nn.template,     `node[${i}].template`)     : undefined,
      branches:     Array.isArray(nn.branches) ? (nn.branches as unknown[]).map(String) : undefined,
      envId:        nn.envId        !== undefined ? str(nn.envId,        `node[${i}].envId`)        : undefined,
    }
  })
  const entryId = str(body.entryId, 'entryId')
  if (!nodes.some(n => n.id === entryId))
    throw new Error(`entryId "${entryId}" does not match any node id`)
  return {
    input, nodes, entryId,
    maxDepth: body.maxDepth !== undefined
      ? num(body.maxDepth, 'maxDepth', MAX_PIPELINE_DEPTH, 1, MAX_PIPELINE_DEPTH)
      : undefined,
  }
}

export function parseVibeRequest(body: unknown): VibeRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const description = str(body.description, 'description')
  if (description.length < 10)               throw new Error('description must be at least 10 characters')
  if (description.length > MAX_VIBE_DESCRIPTION) throw new Error(`description must be <= ${MAX_VIBE_DESCRIPTION} characters`)
  return {
    description,
    name: body.name !== undefined ? str(body.name, 'name') : undefined,
  }
}

export function parseEnvironmentRequest(body: unknown): EnvironmentRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const description = str(body.description, 'description')
  if (description.length < 10)                   throw new Error('description must be at least 10 characters')
  if (description.length > MAX_VIBE_DESCRIPTION)  throw new Error(`description must be <= ${MAX_VIBE_DESCRIPTION} characters`)
  const envType = str(body.envType, 'envType')
  if (!(ENV_TYPES as readonly string[]).includes(envType)) {
    throw new Error(`envType must be one of: ${ENV_TYPES.join(', ')}`)
  }
  const rawModels = body.envModels
  const envModels = Array.isArray(rawModels)
    ? rawModels.slice(0, MAX_ENV_MODELS).filter((m): m is string => typeof m === 'string')
    : undefined
  return {
    description,
    envType,
    envModels,
    name: body.name !== undefined ? str(body.name, 'name') : undefined,
  }
}

// ── App State / Email parsers ─────────────────────────────────────────────────

export interface AppStateValueRequest { key: string; value: string }

export function parseAppStateValueRequest(body: unknown, key: string): AppStateValueRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const value = str(body.value, 'value')
  if (value.length > MAX_APP_STATE_VALUE_LEN)
    throw new Error(`value must be <= ${MAX_APP_STATE_VALUE_LEN} characters`)
  if (key.length > MAX_APP_STATE_KEY_LEN)
    throw new Error(`key must be <= ${MAX_APP_STATE_KEY_LEN} characters`)
  if (!APP_STATE_KEY_RE.test(key))
    throw new Error('key may only contain alphanumeric, dot, underscore, hyphen, or slash')
  return { key, value }
}

export interface EmailRequest {
  to: string
  subject: string
  text: string
  html?: string
}

export function parseEmailRequest(body: unknown): EmailRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const to = str(body.to, 'to')
  if (!/^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/.test(to))
    throw new Error('to must be a valid email address')
  const subject = str(body.subject, 'subject')
  if (subject.length === 0 || subject.length > MAX_EMAIL_SUBJECT_LEN)
    throw new Error(`subject must be a non-empty string <= ${MAX_EMAIL_SUBJECT_LEN} characters`)
  const text = str(body.text, 'text')
  if (text.length === 0 || text.length > MAX_EMAIL_TEXT_LEN)
    throw new Error(`text must be a non-empty string <= ${MAX_EMAIL_TEXT_LEN} characters`)
  return {
    to: to.trim().toLowerCase(),
    subject,
    text,
    html: body.html !== undefined ? str(body.html, 'html') : undefined,
  }
}

// ── App Builder ───────────────────────────────────────────────────────────────

export interface BuildRequest {
  description: string
  name?:       string
  sandboxId?:  string
  model?:      string
}

export function parseBuildRequest(body: unknown): BuildRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const description = str(body.description, 'description')
  if (!description.trim())                           throw new Error('description must not be empty')
  if (description.length > MAX_BUILD_DESCRIPTION_LEN) throw new Error(`description must be <= ${MAX_BUILD_DESCRIPTION_LEN} characters`)
  const name      = body.name      !== undefined ? str(body.name,      'name')      : undefined
  const sandboxId = body.sandboxId !== undefined ? str(body.sandboxId, 'sandboxId') : undefined
  const model     = body.model     !== undefined ? str(body.model,     'model')     : undefined
  if (name      && name.length      > MAX_NAME_LEN) throw new Error(`name must be <= ${MAX_NAME_LEN} characters`)
  if (sandboxId && sandboxId.length > 64)           throw new Error('sandboxId must be <= 64 characters')
  if (model     && model.length     > 128)          throw new Error('model must be <= 128 characters')
  return { description: description.trim(), name, sandboxId, model }
}

// ── Optional-body parsers (used with parseBodyOptional) ───────────────────────

export interface ReindexBody { docIds: string[] | undefined }

export function parseReindexBody(body: unknown): ReindexBody {
  if (body === null || body === undefined) return { docIds: undefined }
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (body.docIds === undefined) return { docIds: undefined }
  if (!Array.isArray(body.docIds)) throw new Error('docIds must be an array')
  return { docIds: body.docIds.map((d, i) => {
    if (typeof d !== 'string') throw new Error(`docIds[${i}] must be a string`)
    return d
  }) }
}

export interface SessionBody { sessionId: string | undefined }

export function parseSessionBody(body: unknown): SessionBody {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (body.sessionId === undefined) return { sessionId: undefined }
  if (typeof body.sessionId !== 'string') throw new Error('sessionId must be a string')
  if (body.sessionId.length > MAX_SESSION_ID_LEN) throw new Error(`sessionId must be <= ${MAX_SESSION_ID_LEN} characters`)
  return { sessionId: body.sessionId || undefined }
}

// ── Guard Laboratory ──────────────────────────────────────────────────────────

export interface GuardProbeRequest { text: string }

export function parseGuardProbeRequest(body: unknown): GuardProbeRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (typeof body.text !== 'string' || !body.text.trim()) throw new Error('text is required')
  if (body.text.length > MAX_GUARD_PROBE_CHARS) throw new Error(`text exceeds ${MAX_GUARD_PROBE_CHARS} character limit`)
  return { text: body.text }
}

// ── Prompt Ablation ───────────────────────────────────────────────────────────

export interface AblationRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export function parseAblationRequest(body: unknown): AblationRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const prompt = str(body.prompt, 'prompt')
  if (prompt.length > MAX_SYSTEM_PROMPT_LEN) throw new Error(`prompt exceeds ${MAX_SYSTEM_PROMPT_LEN} character limit`)
  return {
    prompt,
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2) : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
  }
}

// ── Multi-Turn Drift ──────────────────────────────────────────────────────────

export interface DriftMessage { role: 'user'; content: string }

export interface DriftRequest {
  messages: DriftMessage[]
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export function parseDriftRequest(body: unknown): DriftRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (!Array.isArray(body.messages)) throw new Error('messages must be an array')
  if (body.messages.length < 2 || body.messages.length > MAX_DRIFT_TURNS)
    throw new Error(`messages must have 2–${MAX_DRIFT_TURNS} user turns`)
  const messages: DriftMessage[] = body.messages.map((m: unknown, i: number) => {
    if (!isObj(m)) throw new Error(`messages[${i}] must be an object`)
    if (m.role !== 'user') throw new Error(`messages[${i}].role must be "user"`)
    return { role: 'user' as const, content: str(m.content, `messages[${i}].content`) }
  })
  return {
    messages,
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    temperature:  body.temperature  !== undefined ? num(body.temperature,  'temperature',  DEFAULT_TEMPERATURE, 0, 2) : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
  }
}

// ── Context Stress Test ───────────────────────────────────────────────────────

export interface ContextStressRequest {
  prompt: string
  systemPrompt?: string
  model?: string
  paddingLevels?: number[]
  maxTokens?: number
}

export function parseContextStressRequest(body: unknown): ContextStressRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const defaults = [0, 100, 500, 1000, 2000, 4000]
  let paddingLevels = defaults
  if (body.paddingLevels !== undefined) {
    if (!Array.isArray(body.paddingLevels)) throw new Error('paddingLevels must be an array')
    if (body.paddingLevels.length > MAX_STRESS_LEVELS) throw new Error(`paddingLevels must have at most ${MAX_STRESS_LEVELS} entries`)
    paddingLevels = body.paddingLevels.map((v: unknown, i: number) => {
      if (typeof v !== 'number' || !isFinite(v) || v < 0) throw new Error(`paddingLevels[${i}] must be a non-negative number`)
      return Math.floor(v)
    })
  }
  return {
    prompt:        str(body.prompt, 'prompt'),
    systemPrompt:  body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    model:         body.model        !== undefined ? str(body.model,        'model')        : undefined,
    maxTokens:     body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    paddingLevels,
  }
}

// ── Rubric Evaluator ──────────────────────────────────────────────────────────

export interface RubricCriterion {
  name: string
  description: string
  weight: number
}

export interface EvaluateRequest {
  prompt: string
  systemPrompt?: string
  model?: string
  judgeModel?: string
  samples: number
  criteria: RubricCriterion[]
}

export function parseEvaluateRequest(body: unknown): EvaluateRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  if (!Array.isArray(body.criteria)) throw new Error('criteria must be an array')
  if (body.criteria.length < 1 || body.criteria.length > MAX_RUBRIC_CRITERIA)
    throw new Error(`criteria must have 1–${MAX_RUBRIC_CRITERIA} items`)
  const criteria: RubricCriterion[] = body.criteria.map((c: unknown, i: number) => {
    if (!isObj(c)) throw new Error(`criteria[${i}] must be an object`)
    const name   = str(c.name, `criteria[${i}].name`)
    const desc   = str(c.description, `criteria[${i}].description`)
    const weight = typeof c.weight === 'number' && isFinite(c.weight) && c.weight >= 0 && c.weight <= 1
      ? c.weight : 1 / (body.criteria as unknown[]).length
    return { name, description: desc, weight }
  })
  return {
    prompt:       str(body.prompt, 'prompt'),
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    judgeModel:   body.judgeModel   !== undefined ? str(body.judgeModel,   'judgeModel')   : undefined,
    samples:      body.samples      !== undefined ? num(body.samples, 'samples', 1, 1, MAX_RUBRIC_SAMPLES) : 1,
    criteria,
  }
}

// ── Consistency Probe ─────────────────────────────────────────────────────────

export interface ConsistencyRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  maxTokens?: number
  samples: number
}

export function parseConsistencyRequest(body: unknown): ConsistencyRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return {
    prompt:       str(body.prompt, 'prompt'),
    model:        body.model        !== undefined ? str(body.model,        'model')        : undefined,
    systemPrompt: body.systemPrompt !== undefined ? str(body.systemPrompt, 'systemPrompt') : undefined,
    maxTokens:    body.maxTokens    !== undefined ? num(body.maxTokens,    'maxTokens',    DEFAULT_MAX_TOKENS, 1, 8192) : undefined,
    samples:      body.samples      !== undefined ? num(body.samples,      'samples',      3, 3, MAX_ENTROPY_SAMPLES) : 3,
  }
}

// ── Usage query params ────────────────────────────────────────────────────────

import { isUUID } from './utils'

export type UsageGroupBy = 'model' | 'provider' | 'call_type' | 'sandbox_id' | 'day'

export interface UsageQuery {
  sandboxId?: string
  model?:     string
  provider?:  string
  from?:      number
  to?:        number
  groupBy?:   UsageGroupBy
  limit:      number
}

const USAGE_GROUP_BY_VALUES: UsageGroupBy[] = ['model', 'provider', 'call_type', 'sandbox_id', 'day']

export function parseUsageQuery(params: URLSearchParams): UsageQuery {
  const sandboxId = params.get('sandboxId') ?? undefined
  if (sandboxId !== undefined && !isUUID(sandboxId)) throw new Error('sandboxId must be a valid UUID')

  const model    = params.get('model')    ?? undefined
  const provider = params.get('provider') ?? undefined

  const fromStr = params.get('from')
  const toStr   = params.get('to')
  const from    = fromStr !== null ? parseInt(fromStr, 10) : undefined
  const to      = toStr   !== null ? parseInt(toStr,   10) : undefined
  if (from !== undefined && isNaN(from)) throw new Error('from must be a number (unix ms)')
  if (to   !== undefined && isNaN(to))   throw new Error('to must be a number (unix ms)')

  const groupByStr = params.get('groupBy') ?? undefined
  if (groupByStr !== undefined && !(USAGE_GROUP_BY_VALUES as string[]).includes(groupByStr)) {
    throw new Error(`groupBy must be one of: ${USAGE_GROUP_BY_VALUES.join(', ')}`)
  }
  const groupBy = groupByStr as UsageGroupBy | undefined

  const limit = parseQueryInt(params, 'limit', USAGE_LIMIT_DEFAULT, 1, USAGE_LIMIT_MAX)

  return { sandboxId, model, provider, from, to, groupBy, limit }
}

// ── Saved Pipelines ───────────────────────────────────────────────────────────

export interface CreatePipelineRequest {
  name:        string
  description: string
  nodes:       PipelineNode[]
  entryId:     string
}

export interface PatchPipelineRequest {
  name?:        string
  description?: string
  nodes?:       PipelineNode[]
  entryId?:     string
}

export interface PipelineRunRequest { input: string }

export function parseCreatePipeline(body: unknown): CreatePipelineRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const name = str(body.name, 'name')
  if (name.length > MAX_NAME_LEN) throw new Error(`name must be <= ${MAX_NAME_LEN} characters`)
  const description = body.description !== undefined ? str(body.description, 'description', '') : ''
  if (description.length > MAX_DESCRIPTION_LEN) throw new Error(`description must be <= ${MAX_DESCRIPTION_LEN} characters`)
  // Reuse parsePipelineRequest for node validation; inject a dummy input so it satisfies the schema
  const { nodes, entryId } = parsePipelineRequest({ ...body, input: body.input ?? '' })
  return { name, description, nodes, entryId }
}

export function parsePatchPipeline(body: unknown): PatchPipelineRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const out: PatchPipelineRequest = {}
  if (body.name !== undefined) {
    const name = str(body.name, 'name')
    if (name.length > MAX_NAME_LEN) throw new Error(`name must be <= ${MAX_NAME_LEN} characters`)
    out.name = name
  }
  if (body.description !== undefined) {
    out.description = str(body.description, 'description', '')
    if (out.description.length > MAX_DESCRIPTION_LEN)
      throw new Error(`description must be <= ${MAX_DESCRIPTION_LEN} characters`)
  }
  if (body.nodes !== undefined || body.entryId !== undefined) {
    if (body.nodes === undefined || body.entryId === undefined)
      throw new Error('nodes and entryId must be provided together')
    const { nodes, entryId } = parsePipelineRequest({ nodes: body.nodes, entryId: body.entryId, input: '' })
    out.nodes   = nodes
    out.entryId = entryId
  }
  return out
}

export function parsePipelineRunRequest(body: unknown): PipelineRunRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  return { input: str(body.input, 'input') }
}

// ── Vault Cluster Analysis ────────────────────────────────────────────────────

export interface VaultAnalyzeRequest {
  k:      number
  limit:  number
  tool?:  string
  since?: number
}

export function parseVaultAnalyzeRequest(body: unknown): VaultAnalyzeRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const since = body.since !== undefined
    ? (typeof body.since === 'number' && isFinite(body.since)
        ? body.since
        : (() => { throw new Error('since must be a number (unix ms)') })())
    : undefined
  return {
    k:     body.k     !== undefined ? num(body.k,     'k',     5,   2,  20)  : 5,
    limit: body.limit !== undefined ? num(body.limit, 'limit', 200, 10, 500) : 200,
    tool:  body.tool  !== undefined ? str(body.tool,  'tool')                : undefined,
    since,
  }
}

// ── Probe Webhook ─────────────────────────────────────────────────────────────

const BLOCKED_WEBHOOK_HOSTNAMES = new Set(['localhost', '127.0.0.1', '0.0.0.0', '::1', '[::1]'])

function isPrivateIpv4(ip: string): boolean {
  const parts = ip.split('.').map(Number)
  if (parts.length !== 4 || parts.some(p => !Number.isFinite(p) || p < 0 || p > 255)) return false
  const [a, b] = parts
  if (a === 10) return true
  if (a === 172 && b >= 16 && b <= 31) return true
  if (a === 192 && b === 168) return true
  if (a === 169 && b === 254) return true
  return false
}

function isPrivateIp(host: string): boolean {
  // Strip brackets from IPv6 literals (URL.hostname returns e.g. "[fc00::1]")
  const h = host.replace(/^\[/, '').replace(/\]$/, '').toLowerCase()

  // IPv4-mapped IPv6, dotted form: ::ffff:192.168.1.1
  const v4mapped = h.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/i)
  if (v4mapped) return isPrivateIpv4(v4mapped[1])
  // IPv4-mapped IPv6, hex form (WHATWG URL canonicalizes ::ffff:192.168.1.1 → ::ffff:c0a8:101)
  const v4mappedHex = h.match(/^::ffff:([0-9a-f]{1,4}):([0-9a-f]{1,4})$/)
  if (v4mappedHex) {
    const hi = parseInt(v4mappedHex[1], 16)
    const lo = parseInt(v4mappedHex[2], 16)
    return isPrivateIpv4(`${(hi >> 8) & 0xff}.${hi & 0xff}.${(lo >> 8) & 0xff}.${lo & 0xff}`)
  }
  if (/^\d+\.\d+\.\d+\.\d+$/.test(h)) return isPrivateIpv4(h)

  // IPv6 literals contain colons; only then apply IPv6 range checks
  if (h.includes(':')) {
    if (h === '::1') return true            // loopback ::1/128
    if (/^fe[89ab]/.test(h)) return true    // link-local fe80::/10
    if (/^f[cd]/.test(h)) return true       // unique-local fc00::/7
  }
  return false
}

export function parseWebhookUrl(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined
  if (typeof v !== 'string') throw new Error('webhookUrl must be a string')
  if (v.length === 0) return undefined
  if (!v.startsWith('https://')) throw new Error('webhookUrl must start with https://')
  if (v.length > MAX_WEBHOOK_URL_LEN) throw new Error(`webhookUrl must be <= ${MAX_WEBHOOK_URL_LEN} characters`)
  let parsed: URL
  try { parsed = new URL(v) } catch { throw new Error('webhookUrl must be a valid URL') }
  const host = parsed.hostname.toLowerCase()
  if (BLOCKED_WEBHOOK_HOSTNAMES.has(host)) throw new Error('webhookUrl must not target localhost')
  if (host.endsWith('.internal') || host.endsWith('.local') || host.endsWith('.localhost'))
    throw new Error('webhookUrl must not target internal hostnames')
  if (isPrivateIp(host)) throw new Error('webhookUrl must not target private IP ranges')
  return v
}

// ── TTS request ───────────────────────────────────────────────────────────────

export interface TTSRequest {
  provider: 'elevenlabs' | 'cartesia'
  text: string
  voiceId?: string
  modelId?: string
  voice?: { mode: string; id: string }
  outputFormat?: { container: string; encoding: string; sampleRate: number }
}

export function parseTTSRequest(body: unknown): TTSRequest {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const providerRaw = typeof body.provider === 'string' ? body.provider : 'elevenlabs'
  if (providerRaw !== 'elevenlabs' && providerRaw !== 'cartesia')
    throw new Error('provider must be "elevenlabs" or "cartesia"')
  const provider = providerRaw as 'elevenlabs' | 'cartesia'
  const text = str(body.text, 'text')
  if (text.length === 0) throw new Error('text is required')
  if (text.length > MAX_TTS_TEXT_LEN) throw new Error(`text must be <= ${MAX_TTS_TEXT_LEN} characters`)
  const result: TTSRequest = { provider, text }
  if (body.voiceId    !== undefined) result.voiceId  = str(body.voiceId, 'voiceId')
  if (body.modelId    !== undefined) result.modelId  = str(body.modelId, 'modelId')
  if (body.voice      !== undefined) {
    if (!isObj(body.voice)) throw new Error('voice must be an object')
    result.voice = { mode: str(body.voice.mode, 'voice.mode'), id: str(body.voice.id, 'voice.id') }
  }
  if (body.outputFormat !== undefined) {
    if (!isObj(body.outputFormat)) throw new Error('outputFormat must be an object')
    result.outputFormat = {
      container:  str(body.outputFormat.container,  'outputFormat.container'),
      encoding:   str(body.outputFormat.encoding,   'outputFormat.encoding'),
      sampleRate: num(body.outputFormat.sampleRate, 'outputFormat.sampleRate', 44100, 8000, 48000),
    }
  }
  return result
}

// ── Vault semantic search ──────────────────────────────────────────────────────

export interface PatchSandboxRequest {
  name?: string
  description?: string
  systemPrompt?: string
  model?: string
  temperature?: number
  maxTokens?: number
  tools?: Tool[]
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
}

export function parsePatchSandboxRequest(body: unknown): PatchSandboxRequest {
  if (!isObj(body)) throw new Error('Body must be a JSON object')
  const out: PatchSandboxRequest = {}
  if (body.name         !== undefined) out.name         = str(body.name, 'name').slice(0, MAX_NAME_LEN)
  if (body.description  !== undefined) out.description  = str(body.description, 'description').slice(0, MAX_DESCRIPTION_LEN)
  if (body.systemPrompt !== undefined) {
    const sp = str(body.systemPrompt, 'systemPrompt')
    if (sp.length > MAX_SYSTEM_PROMPT_LEN) throw new Error(`systemPrompt must be <= ${MAX_SYSTEM_PROMPT_LEN} characters`)
    out.systemPrompt = sp
  }
  if (body.model        !== undefined) out.model        = str(body.model, 'model')
  if (body.temperature  !== undefined) out.temperature  = num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2)
  if (body.maxTokens    !== undefined) out.maxTokens    = num(body.maxTokens, 'maxTokens', DEFAULT_MAX_TOKENS, 64, 8192)
  if (body.ragEnabled   !== undefined) out.ragEnabled   = bool(body, 'ragEnabled', false)
  if (body.guardMode    !== undefined) {
    const gm = str(body.guardMode, 'guardMode')
    if (gm !== 'strict' && gm !== 'audit' && gm !== 'off')
      throw new Error("guardMode must be 'strict', 'audit', or 'off'")
    out.guardMode = gm
  }
  if (body.tools !== undefined) {
    if (!Array.isArray(body.tools)) throw new Error('tools must be an array')
    out.tools = (body.tools as unknown[]).slice(0, 20).map((t, i) => parseTool(t, i))
  }
  return out
}

export function parsePatchEnvironmentRequest(body: unknown): {
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  envModels?: string[]
} {
  if (!isObj(body)) throw new Error('Body must be a JSON object')
  const out: { systemPrompt?: string; temperature?: number; maxTokens?: number; envModels?: string[] } = {}
  if (body.systemPrompt !== undefined) out.systemPrompt = str(body.systemPrompt, 'systemPrompt')
  if (body.temperature  !== undefined) out.temperature  = num(body.temperature, 'temperature', DEFAULT_TEMPERATURE, 0, 2)
  if (body.maxTokens    !== undefined) out.maxTokens    = num(body.maxTokens, 'maxTokens', DEFAULT_MAX_TOKENS, 64, 8192)
  if (body.envModels    !== undefined) {
    if (!Array.isArray(body.envModels) || body.envModels.length === 0 || body.envModels.length > MAX_ENV_MODELS)
      throw new Error(`envModels must be an array of 1–${MAX_ENV_MODELS} model strings`)
    if (!(body.envModels as unknown[]).every((m: unknown) => typeof m === 'string'))
      throw new Error('All envModels entries must be strings')
    out.envModels = body.envModels as string[]
  }
  return out
}

export function parseVaultSearchRequest(body: unknown): { q: string; limit: number; tool: string | null } {
  if (!isObj(body)) throw new Error('Request body must be a JSON object')
  const q = str(body.q, 'q')
  if (!q.trim()) throw new Error('q must not be empty')
  return {
    q,
    limit: body.limit !== undefined ? num(body.limit, 'limit', 20, 1, AI_SEARCH_MAX_RESULTS) : 20,
    tool:  body.tool  !== undefined ? str(body.tool, 'tool') : null,
  }
}
