import type { Handler } from '../../lib/http'
import { genNonce, htmlHeaders, sharedCss, navHtml, escJs } from './shared'

// ── Builds gallery page (/builds) — App Builder output ───────────────────────

export function buildsGalleryHtml(nonce: string): string { return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<meta name="robots" content="noindex"/>
<title>Whisper — Builds</title>
${sharedCss()}
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text);min-height:100dvh}
.topnav{position:sticky;top:0;z-index:10}
main{max-width:1100px;margin:0 auto;padding:32px 24px;min-height:calc(100dvh - 48px);display:flex;flex-direction:column}
h2{font-size:22px;font-weight:700;margin-bottom:6px}
.sub{color:var(--muted);font-size:13px;margin-bottom:28px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:10px;display:flex;flex-direction:column;overflow:hidden;transition:border-color .15s,transform .15s}
.card:hover{border-color:var(--accent);transform:translateY(-2px)}
.card-thumb{width:100%;height:120px;background:var(--bg);display:flex;align-items:center;justify-content:center;border-bottom:1px solid var(--border);overflow:hidden}
.card-thumb img{width:100%;height:100%;object-fit:cover}
.card-thumb-placeholder{font-size:32px;opacity:.2}
.card-body{padding:14px 16px;display:flex;flex-direction:column;gap:8px;flex:1}
.card-name{font-size:14px;font-weight:600}
.card-desc{font-size:12px;color:var(--muted);flex:1;line-height:1.5;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.card-foot{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.status-badge{font-size:10px;padding:2px 8px;border-radius:99px;font-family:var(--mono);flex-shrink:0}
.status-complete{background:#10b98122;color:var(--green)}
.status-idle{background:#6366f122;color:var(--accent2)}
.status-other{background:#f59e0b22;color:#f59e0b}
.card-date{font-size:11px;color:var(--muted);margin-left:auto}
.open-btn{padding:8px 16px;min-height:36px;border-radius:var(--radius);background:var(--accent);color:#fff;border:none;font-size:12px;font-weight:500;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;gap:4px}
.open-btn:hover{background:#4f46e5}
.open-btn:focus-visible{outline:2px solid var(--accent2);outline-offset:2px}
.act-btn{padding:7px 12px;min-height:36px;border-radius:var(--radius);background:none;border:1px solid var(--border);color:var(--muted);font-size:11px;font-weight:500;cursor:pointer;display:inline-flex;align-items:center;gap:4px;transition:border-color .15s,color .15s;font-family:inherit}
.act-btn:hover{border-color:var(--accent2);color:var(--text)}
.act-btn:focus-visible{outline:2px solid var(--accent2);outline-offset:2px}
.act-btn:disabled{opacity:.5;cursor:not-allowed}
.act-del:hover{border-color:var(--red);color:var(--red)}
.skeleton{background:var(--surface);border:1px solid var(--border);border-radius:10px;height:240px;animation:pulse 1.4s ease-in-out infinite}
.newbuild{padding:4px 10px;border:1px solid var(--border);border-radius:var(--radius);color:var(--accent2);font-size:11px;transition:border-color .15s,color .15s}
.newbuild:hover{border-color:var(--accent2)}
@media(max-width:480px){.card-body{padding:10px 12px}}
</style>
</head>
<body>
${navHtml('builds', '  <a href="/vibe.html" class="navlink newbuild">+ New Build</a>')}
<main>
  <h2>Your Builds</h2>
  <p class="sub">Multi-file web apps generated by the App Builder. Describe what you want and the AI writes the full app — HTML, CSS, JS, and more.</p>
  <div id="grid" class="grid" role="list"></div>
</main>
<script nonce="${nonce}">
async function load(){
  const grid = document.getElementById('grid')
  grid.innerHTML = [1,2,3].map(function(){ return '<div class="skeleton" role="listitem" aria-hidden="true"></div>' }).join('')
  try{
    const r = await fetch('/api/v2/build')
    const d = await r.json()
    if(!d.ok || !d.data.builds || !d.data.builds.filter(Boolean).length){
      grid.style.cssText='flex:1;display:flex;align-items:center;justify-content:center'
      grid.innerHTML='<div class="empty"><h3>No builds yet</h3><p>Use the Vibe coder to generate your first multi-file app or dashboard.</p><a href="/vibe.html" class="empty-cta">Open Vibe Coder →</a></div>'
      return
    }
    grid.innerHTML=''
    const builds = d.data.builds.filter(Boolean)
    builds.forEach(function(build, i){
      if(!build) return
      const date=new Date(build.createdAt||0).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})
      const status=build.status||'idle'
      const statusCls=status==='complete'?'status-complete':status==='idle'?'status-idle':'status-other'
      const delay=Math.min(i,10)*50
      const thumbUrl='/api/v2/build/'+esc(build.id)+'/thumbnail'
      grid.insertAdjacentHTML('beforeend',\`
        <div class="card" role="listitem" style="animation:cardIn .2s ease-out both;animation-delay:\${delay}ms" data-id="\${esc(build.id)}" data-name="\${esc(build.name||build.id)}">
          <div class="card-thumb">
            <img src="\${thumbUrl}" alt="" loading="lazy" onerror="this.parentNode.innerHTML='<span class=\\"card-thumb-placeholder\\">◈</span>'"/>
          </div>
          <div class="card-body">
            <span class="card-name">\${esc(build.name||build.id)}</span>
            <p class="card-desc">\${esc(build.description||'No description')}</p>
            <div class="card-foot">
              <span class="status-badge \${esc(statusCls)}">\${esc(status)}</span>
              <span class="card-date">\${date}</span>
            </div>
            <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:2px">
              <a href="/build/\${esc(build.id)}" class="open-btn">Open <span aria-hidden="true">→</span></a>
              \${status==='complete' ? '<button class="act-btn deploy-btn" data-id="'+esc(build.id)+'" data-name="'+esc(build.name||build.id)+'">Deploy ↑</button>' : ''}
              <button class="act-btn act-del delete-btn" data-id="\${esc(build.id)}" data-name="\${esc(build.name||build.id)}">Delete</button>
            </div>
          </div>
        </div>
      \`)
    })
    document.getElementById('grid').addEventListener('click', handleCardAction)
  }catch(e){
    grid.style.cssText='flex:1;display:flex;align-items:center;justify-content:center'
    grid.innerHTML='<div class="empty"><h3>Failed to load builds</h3><p>'+esc(String(e))+'</p></div>'
  }
}

async function handleCardAction(e){
  const deploy = e.target.closest('.deploy-btn')
  const del    = e.target.closest('.delete-btn')
  if(deploy) await doDeploy(deploy.dataset.id, deploy.dataset.name, deploy)
  if(del)    await doDelete(del.dataset.id, del.dataset.name, del)
}

async function doDeploy(id, name, btn){
  btn.disabled=true; btn.textContent='Deploying…'
  try{
    const r=await fetch('/api/v2/build/'+id+'/deploy',{method:'POST'})
    const d=await r.json()
    if(!d.ok)throw new Error(d.error||'Deploy failed')
    alert('Deployed to '+d.data.deploymentUrl)
    btn.textContent='Deployed ✓'
  }catch(e){ btn.disabled=false; btn.textContent='Deploy ↑'; alert('Deploy failed: '+String(e)) }
}

async function doDelete(id, name, btn){
  if(!confirm('Delete build "'+name+'"? This cannot be undone.')) return
  btn.disabled=true;btn.textContent='Deleting…'
  try{
    const r=await fetch('/api/v2/build/'+id,{method:'DELETE'})
    const d=await r.json()
    if(!d.ok)throw new Error(d.error||'Delete failed')
    btn.closest('.card').remove()
  }catch(e){btn.disabled=false;btn.textContent='Delete';alert('Delete failed: '+String(e))}
}

${escJs}

load()
</script>
</body>
</html>` }

export const buildsGallery: Handler = (_req, _env) => {
  const nonce = genNonce()
  return Promise.resolve(new Response(buildsGalleryHtml(nonce), { headers: htmlHeaders(nonce) }))
}
