// ── Domain types ──────────────────────────────────────────────────────────────

export interface TextBlock {
  type: 'text'
  text: string
}

export interface ImageBlock {
  type: 'image'
  mediaType: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp'
  data: string  // base64, no data: URI prefix
}

export type ContentBlock = TextBlock | ImageBlock

export interface Message {
  role: 'system' | 'user' | 'assistant'
  content: string | ContentBlock[]
  timestamp: number
}

export interface ToolParam {
  type: 'string' | 'number' | 'boolean' | 'array' | 'object'
  description: string
  required?: boolean
}

export interface Tool {
  name: string
  description: string
  parameters: Record<string, ToolParam>
}

export interface SandboxConfig {
  id: string
  name: string
  description: string
  systemPrompt: string
  tools: Tool[]
  model: string
  temperature: number
  maxTokens: number
  memory: Message[]
  createdAt: number
  updatedAt: number
  integrityHash?: string
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
  appHtml?: string   // custom HTML page served at /app/:id (generated by Vibe Builder)
  envType?: string   // chat environment type: general | coding | research | structured
  envModels?: string[]  // ordered model list for compare mode (1–MAX_ENV_MODELS)
}

// ── Request shapes ─────────────────────────────────────────────────────────────

export interface CompleteRequest {
  prompt?: string
  messages?: Message[]
  systemPrompt?: string
  model?: string
  temperature?: number
  maxTokens?: number
  // Advanced controls — mirrors CompletionOpts in ai.ts
  tools?: Tool[]
  toolChoice?: 'auto' | 'required' | 'none'
  responseFormat?: 'json' | 'text'
  jsonSchema?: Record<string, unknown>  // OpenAI json_schema strict mode (overrides responseFormat)
  groundingEnabled?: boolean
  reasoningEffort?: 'low' | 'medium' | 'high'
  thinking?: number
  // AI Gateway extended controls
  byokAlias?:        string   // cf-aig-byok-alias — named credential in Secrets Store
  zdr?:              boolean  // cf-aig-zdr: true — Zero Data Retention (Unified Billing only)
  collectLogPayload?: boolean // false → cf-aig-collect-log-payload: false (suppress body logging)
  fallbackModel?:    string   // tried once if the primary model throws
}

export interface EmbedRequest {
  text: string | string[]
  model?: string
}

export interface ImageRequest {
  prompt: string
  model?: string
  steps?: number
}

export interface CreateSandboxRequest {
  name: string
  description: string
  systemPrompt: string
  tools: Tool[]
  model: string
  temperature: number
  maxTokens: number
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
  appHtml?: string
}

export interface CompareRequest {
  prompt: string
  models: string[]
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export interface SweepRequest {
  prompt: string
  temperatures: number[]
  model?: string
  systemPrompt?: string
  maxTokens?: number
  samples?: number
}

export interface RunSandboxRequest {
  message: string
  sessionId?: string   // named conversation thread (empty = default shared memory)
}

export interface VibeRequest {
  description: string
  name?: string
}

export interface EnvironmentRequest {
  description: string
  envType: string
  envModels?: string[]
  name?: string
}

// ── Whisperer request types ───────────────────────────────────────────────────

export interface SensitivityRequest {
  prompt: string
  variants: number
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

export interface ClusterRequest {
  texts: string[]
  k: number
  model?: string
}

export interface CotRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  samples: number
}

export interface EntropyRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature: number
  maxTokens?: number
  samples: number
}

export interface ArchaeologyRequest {
  targetResponse: string
  probe: string
  model?: string
  candidates: number
  maxTokens?: number
}

export interface PipelineRoute {
  condition: string
  nextId: string
}

export interface PipelineNode {
  id: string
  type: 'complete' | 'classify' | 'guard' | 'transform' | 'parallel' | 'env_resolve'
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  template?: string
  branches?: string[]
  select?: 'first' | 'best' | 'all'
  envId?: string  // for env_resolve: resolves environment config and outputs it as JSON
  routes: PipelineRoute[]
}

export interface PipelineRequest {
  input: string
  nodes: PipelineNode[]
  entryId: string
  maxDepth?: number
}

export interface ThinkRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  maxTokens?: number
  budgetTokens?: number
}

// ── App State / Email types ───────────────────────────────────────────────────

export interface AppStateValueRequest { key: string; value: string }

export interface EmailRequest {
  to: string
  subject: string
  text: string
  html?: string
}

// ── App Builder ───────────────────────────────────────────────────────────────

export interface BuildRequest {
  description: string
  name?:       string
  sandboxId?:  string
  model?:      string
}

// ── Optional-body parsers (used with parseBodyOptional) ───────────────────────

export interface ReindexBody { docIds: string[] | undefined }

export interface SessionBody { sessionId: string | undefined }

// ── Guard Laboratory ──────────────────────────────────────────────────────────

export interface GuardProbeRequest { text: string }

// ── Prompt Ablation ───────────────────────────────────────────────────────────

export interface AblationRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

// ── Multi-Turn Drift ──────────────────────────────────────────────────────────

export interface DriftMessage { role: 'user'; content: string }

export interface DriftRequest {
  messages: DriftMessage[]
  model?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

// ── Context Stress Test ───────────────────────────────────────────────────────

export interface ContextStressRequest {
  prompt: string
  systemPrompt?: string
  model?: string
  paddingLevels?: number[]
  maxTokens?: number
}

// ── Rubric Evaluator ──────────────────────────────────────────────────────────

export interface RubricCriterion {
  name: string
  description: string
  weight: number
}

export interface EvaluateRequest {
  prompt: string
  systemPrompt?: string
  model?: string
  judgeModel?: string
  samples: number
  criteria: RubricCriterion[]
}

// ── Consistency Probe ─────────────────────────────────────────────────────────

export interface ConsistencyRequest {
  prompt: string
  model?: string
  systemPrompt?: string
  maxTokens?: number
  samples: number
}

// ── Usage query params ────────────────────────────────────────────────────────

export type UsageGroupBy = 'model' | 'provider' | 'call_type' | 'sandbox_id' | 'day'

export interface UsageQuery {
  sandboxId?: string
  model?:     string
  provider?:  string
  from?:      number
  to?:        number
  groupBy?:   UsageGroupBy
  limit:      number
}

// ── Saved Pipelines ───────────────────────────────────────────────────────────

export interface CreatePipelineRequest {
  name:        string
  description: string
  nodes:       PipelineNode[]
  entryId:     string
}

export interface PatchPipelineRequest {
  name?:        string
  description?: string
  nodes?:       PipelineNode[]
  entryId?:     string
}

export interface PipelineRunRequest { input: string }

// ── Vault Cluster Analysis ────────────────────────────────────────────────────

export interface VaultAnalyzeRequest {
  k:      number
  limit:  number
  tool?:  string
  since?: number
}

// ── TTS request ───────────────────────────────────────────────────────────────

export interface TTSRequest {
  provider: 'elevenlabs' | 'cartesia'
  text: string
  voiceId?: string
  modelId?: string
  voice?: { mode: string; id: string }
  outputFormat?: { container: string; encoding: string; sampleRate: number }
}

// ── Vault semantic search ──────────────────────────────────────────────────────

export interface PatchSandboxRequest {
  name?: string
  description?: string
  systemPrompt?: string
  model?: string
  temperature?: number
  maxTokens?: number
  tools?: Tool[]
  guardMode?: 'strict' | 'audit' | 'off'
  ragEnabled?: boolean
}
